basePath: /
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact:
    email: support@example.com
    name: API Support
    url: http://www.example.com/support
  description: API Gateway component for Nexus-enhanced Telemetry Pipeline providing
    REST API endpoints for querying telemetry data, with GraphQL and WebSocket support
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: http://swagger.io/terms/
  title: Nexus Telemetry API Gateway
  version: "2.0"
paths:
  /api/v1/gpus:
    get:
      description: Return a list of all GPUs for which telemetry data is available
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: List all GPUs
      tags:
      - gpus
  /api/v1/gpus/{id}/telemetry:
    get:
      description: Return all telemetry entries for a specific GPU, ordered by time
      parameters:
      - description: GPU ID
        in: path
        name: id
        required: true
        type: string
      - description: Start time (RFC3339 format)
        in: query
        name: start_time
        type: string
      - description: End time (RFC3339 format)
        in: query
        name: end_time
        type: string
      - description: Limit number of results (default 100)
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Query telemetry by GPU
      tags:
      - telemetry
schemes:
- http
- https
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
